version: '3.8'

services:
  # Message Broker
  messagebroker:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    networks:
      - cybernet
 
# Containers Internal Network
networks:
  cybernet:
    driver: bridge