version: '3.8'

services:
  # Message Broker
  messagebroker:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    networks:
      - cybernet

  # Database
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - 3306:3306
    volumes:
      - users_db:/var/lib/mysql

  # Database Client
  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
 
# Volume - To persist data
volumes:
  users_db:

# Containers Internal Network
networks:
  cybernet:
    driver: bridge